language: minimal

script:
  - for i in `seq 42`; do sleep 1; echo $i; done
  - curl -X POST -H Content-Type\:\ application/json -H Authorization\:\ token\ $TRAVIS_TOKEN https://api.travis-ci.com/repo/monperrus\%2Ftravis-metronome/requests
  

