language: minimal

script:
  - for i in `seq 42`; do sleep 1; echo $i; done
  - curl -s -X POST -H "Content-Type: application/json" -H "Accept: application/json" -H "Travis-API-Version: 3" https://foo.com

